# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_downloaddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='analytics_exp',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='correct_post_pg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='corrected_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ctc',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_employer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nearest_city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pg_cource',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pg_institute',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pg_passing_year',
            field=models.CharField(blank=True, choices=[(2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950)], max_length=4),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='post_pg_cource',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='prefered_location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.CharField(choices=[(b'yes', b'Yes'), (b'no', b'No')], default=b'yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skill',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trier1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ug_cource',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ug_institute',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ug_passing_year',
            field=models.IntegerField(choices=[(2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950)], default=(2016, 2016), max_length=4),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='downloaddetail',
            name='total_downloads',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='downloaddetail',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
